import { PAYMENT_METHOD_CONFIG } from '../paymentMethodConfiguration';

// paymentMethodConfiguration.js is generated by scripts/generate-payment-config.mjs and edited by
// subscribers, so this suite avoids asserting specific example values. Payer-facing strings may be
// plain literals OR Custom Label references (labels.<name>); it only guards that none is left empty.
// The "you can use a Custom Label" example lives in the README and the generator comment.
describe('paymentMethodConfiguration localization', () => {
    it('every payer-facing config string resolves to a non-empty value', () => {
        for (const method of PAYMENT_METHOD_CONFIG) {
            expect(method.displayLabel).toBeTruthy();
            if (method.redirectInstruction != null) {
                expect(method.redirectInstruction).toBeTruthy();
            }
            for (const param of method.parameters ?? []) {
                if (param.visibleToCustomer) {
                    expect(param.displayLabel).toBeTruthy();
                }
            }
        }
    });
});
